### PR TITLE
perf(scroll): prevent unneeded forced synchronous layout on update

### PR DESCRIPTION
**Pull request by STRML**
In the case where new items are added or the component is otherwise rerendered,
this avoids an expensive relayout in getScroll() where the result would not change.

In a production application I see as much as 9ms on unneeded synchronous
layout when this happens.

### CODE REVIEW

**Comment by STRML** [comment]
This is minified production code, but it gives an idea of how expensive this synchronous layout can be. This happens when I append an item to the top of the list, which should not require scroll recalculation.

screen shot 2018-06-02 at 12 27 43 pm

**Comment by caseywebdev** [comment]
LGTM, thanks!

**Comment by STRML** [comment]
Thanks for the very quick merge!

**Comment by caseywebdev** [comment]
Published in `0.8.9`

**Pull request merged**
